### ISSUE TITLE
Frank ToDo

### ISSUE THREAD

**Issue by Murkantilism** [ronnymraz/skylabgame#1]
- [x] Blob Enemy model, rig, animation
- [x] Wall Saw model, animation
- [x] WingHelm jump animation
- [x] WingHelm slide animation
- [x] WingHelm transition animation
- [x] Pickup texture
- [x] Powerup animations
- [x] Powerup texture
