### ISSUE TITLE
Deniz ToDo

### ISSUE THREAD

**Issue by Murkantilism** [ronnymraz/skylabgame#3]
- [ ] Tweak and perfect endless runner mechanic
- [x] Implement Item abstract base class
- [x] Implement Obstacle abstract base class
- [x] Implement Puzzle abstract base class
- [ ] Implement an item, obstacle, and puzzle
- [ ] Implement DoorTimer script

**Comment by Murkantilism** [comment]
IMCOMPLETE SEE TICKET #15
