### ISSUE TITLE
Ronny ToDo

### ISSUE THREAD

**Issue by ronnymraz** [ronnymraz/skylabgame#5]
- [x] Mockup Platform Puzzle

- [x] Seesaw Puzzle

- [x] Trampoline Puzzle

- [x] Speed Ramp Puzzle

- [x] Initial Wall height for maze walls

- [x] initial Camera Angle for maze traversal
